Add crashlytics module
tapptitude/AndroidKotlinMVVMTemplate pull request #18
Opened 2022-04-05 13:19 UTC by alexhasmasan

2022-04-14 09:33 UTC, greenfodor approved these changes

2022-05-13 14:26 UTC, laurentiuonac requested changes

2022-05-13 14:26 UTC, laurentiuonac commented on crashlytics/src/main/java/com/tapptitude/crashlytics/Crashlytics.kt
> +    fun setLog(message: String)
I would go with addLog as we can add multiple ones instead of setting one.

2022-05-17 13:22 UTC, laurentiuonac approved these changes

2022-05-31 12:07 UTC, laurentiuonac commented
@alexhasmasan can you please update the PR?

2022-05-31 12:23 UTC, greenfodor approved these changes

2022-06-02 15:15 UTC, merged